## load required R packages
```{r}
packages = c('tidyverse', 'tidytext', 'tm', 'SnowballC', 'wordcloud', 'wordcloud2', 'RColorBrewer', 'stringi', 'readr', 'stringr', 'topicmodels', 'dplyr', 'plotly', 'parallelPlot')
for (p in packages){
if(!require(p, character.only = T)){
install.packages(p)
}
library(p, character.only = T)
}
```

## read in Airbnb.csv
```{r}
Airbnb <- read_csv("data/Airbnb.csv")

#str(Airbnb_desc)
```

```{r}
# create a corpus

# Airbnb_desc <- Corpus(VectorSource(Airbnb$description)))

Airbnb_orange <- Airbnb %>% filter(region_name == 'Orange')

Airbnb_desc <- Corpus(VectorSource(Airbnb_orange$description))

#see how to clean up the words in the word cloud

# tokenization and cleaning tokens
Airbnb_corpus <- Airbnb_desc %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
Airbnb_corpus <- tm_map(Airbnb_corpus, content_transformer(tolower))
Airbnb_corpus <- tm_map(Airbnb_corpus, removeWords, c(stopwords("english"), "orange"))

gsub(c("%br", "%bbr"), "", Airbnb_corpus)

# create the term document matrix
Airbnb_tdm <- TermDocumentMatrix(Airbnb_corpus)
matrix <- as.matrix(Airbnb_tdm)
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)
```

```{r}
# create the word cloud
wordcloud(words = df$word, freq = df$freq, min.freq = 50, max.words=400, random.order=FALSE, rot.per=0.35, scale=c(3.5, 0.1), colors=brewer.pal(8, "Dark2"))

wordcloud2(data=df, size = 0.7, shape = 'pentagon')

```

```{r}
#> A LDA_VEM topic model with 5 topics.
Airbnb_lda <- LDA(Airbnb_tdm, k = 2)
Airbnb_lda

Airbnb_topics <- tidy(Airbnb_lda, matrix = "beta")
Airbnb_topics

Airbnb_top_terms <- Airbnb_topics %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

Airbnb_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```

```{r}
# Airbnb_desc_Corpus

# getTransformations()

# gsub("<br />", " ", Airbnb_desc_Corpus)
# gsub("é", "e", Airbnb_desc_Corpus)

# view(guess_encoding(Airbnb_desc_Corpus))

#guess_encoding(readr_example("mtcars.csv"))
#view(guess_encoding(readr_example("mtcars.csv")))

#iconv(Airbnb_desc_Corpus, from = "windows-1252", to = "UTF-8", sub = " ")
#iconv(Airbnb_desc_Corpus, from = "ASCII", to = "UTF-8", sub = " ")

#iconvlist()

# Delete non-alphanumeric characters
#str_replace_all(Airbnb_desc_Corpus, "[^[:alnum:]]", "")

# to lower case
Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus, stri_trans_tolower)

# remove punctuation
Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus, removePunctuation)

# str_replace_all(Airbnb_desc_Corpus, "br", " ")

# remove stopwords and others
# Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus, removeWords, stopwords("en"))

# view(guess_encoding(Airbnb_desc_Corpus[-1]))

# remove numbers
Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus, removeNumbers)

# remove extra white space
Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus, stripWhitespace)

# Stem Document
Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus, stemDocument,"english")
#writeLines(as.character(listings_corpus[[1]]))

Airbnb_desc_Corpus <- tm_map(Airbnb_desc_Corpus[35799], removeWords, stopwords("english"))

```

```{r}
# Document term matrix
dtm <- DocumentTermMatrix(Airbnb_desc_Corpus)
# check total frequency of words
freq <- colSums(as.matrix(dtm))
freq
# convert to a data frame
freq_df <- data.frame(word = names(freq),freq=freq)
head(freq_df, 10)
view(freq_df)
# check the frequncey
summary(freq_df$freq)
dim(freq_df)
```

#create word cloud
```{r}
wordcloud(words = freq_df$word, freq = freq_df$freq, min.freq = 50,
          random.order=FALSE,
          rot.per=0.5,
          colors=brewer.pal(8, "Dark2"))
```

